language:
  - php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install: composer install

script: phpunit --coverage-text --coverage-clover=coverage.xml

after_success:
  - php vendor/bin/coveralls
