language:
  - php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*

install: composer install

script: phpunit --coverage-text --coverage-clover=coverage.xml

after_success:
  - php vendor/bin/coveralls
